---
title: "Gov 51 PS1"
author: "Sage Piekarski" 
---

1.  Project Setup

```{r}

#Git URL: visual https://github.com/sagepiekarski-ai/gov51-ps1.git

#loading ipumsr
##install.packages('ipumsr')
library('ipumsr')

#loading tidyverse
##install.packages("tidyverse")
library(tidyverse)

#instructions from IPUMS page
ddi <- read_ipums_ddi("data/raw/acs2024.xml")
acs2024 <- read_ipums_micro(ddi)

#save as CSV per instructions
write_csv(acs2024, "data/raw/acs2024.csv")

```

2.  Get to know your data.

```{r}

#Question 1

#loading tidyverse
##install.packages("tidyverse")
library(tidyverse)

#read csv
acs2024csv <- read.csv("data/raw/acs2024.csv")

# removes two additinal variables added in the data export
acs2024_clean <- acs2024csv %>% 
  select(STATEFIP, AGE, SEX, EDUC, EMPSTAT, TRANTIME, INCTOT)

#Question 2

#STATEFIP reports the state in which the household was located using the Federal
#Information Processing Standards (FIPS) coding scheme.

#AGE reports the person's age in years as of the last birthday.

#SEX reports whether the person was male or female.

#EDUC indicates respondents' educational attainment, as measured by the highest 
#year of school or degree completed.

#EMPSTAT indicates whether the respondent was a part of the labor force -- 
#working or seeking work -- and, if so, whether the person was currently 
#unemployed. 

#TRANTIME reports the total amount of time, in minutes, that it usually took the 
#respondent to get from home to work last week. A code of zero represents 

#INCTOT reports each respondent's total pre-tax personal income or losses from 
#all sources for the previous year. Measured in $.

#PERWT indicates how many persons in the U.S. population are represented by a 
#given person in an IPUMS sample.

#female is 1 if female and 0 if male.

#Question 3 Create New Variables
acs2024_clean <- acs2024_clean %>% 
  mutate(female = case_when(SEX == 1 ~ 0, SEX == 2 ~ 1),
          less_than_hs = case_when(EDUC %in% c(1, 2, 3, 4, 5) ~ 1, TRUE ~ 0),
          hs_only = case_when(EDUC == 6 ~ 1, TRUE ~ 0), 
          some_college = case_when(EDUC %in% c(7, 8) ~ 1, TRUE ~ 0), 
         college_only = case_when(EDUC %in% c(9, 10) ~ 1, TRUE ~ 0),
         advanced_degree = case_when(EDUC == 11 ~ 1, TRUE ~ 0),
         employed = case_when(EMPSTAT == 1 ~ 1, TRUE ~ 0),
         unemployed = case_when(EMPSTAT == 2 ~ 1, TRUE ~ 0), 
         not_in_labor_force = case_when(EMPSTAT == 3 ~ 1, TRUE ~ 0))
         
#Question 4 if you accidentally treated “N/A” codes as real zeros when 
#calculating summary statistics you could run into some major problems. For 
#instance, some zeros represent actual values rather than N/A codes. As such, 
#if you were to treat n/a or missing values as zeros, it would count more zero 
#values than there truly are. A good example of this could be the female 
#variable in which a zero represents a male; if we treated all n/a counts 
#observations as zeros, we would get a count of males significantly larger 
#than the true value. 

##Question 5 
#Create a Summary Statistics Table 
summary_stats_table  <- data.frame(
  Variable = c("Age", "Female", "Less than High School", "High School Only",
  "Some College", "College Only", "Advanced Degree", "Employed", "Unemployed",
  "Not in Labor Force", "Commute Time (mins)", "Total Income ($)"),
  N = c(sum(!is.na(acs2024_clean$AGE)),
        sum(!is.na(acs2024_clean$female)),
        sum(!is.na(acs2024_clean$less_than_hs)),
        sum(!is.na(acs2024_clean$hs_only)),
        sum(!is.na(acs2024_clean$some_college)),
        sum(!is.na(acs2024_clean$college_only)),
        sum(!is.na(acs2024_clean$advanced_degree)),
        sum(!is.na(acs2024_clean$employed)),
        sum(!is.na(acs2024_clean$unemployed)),
        sum(!is.na(acs2024_clean$not_in_labor_force)),
        sum(!is.na(acs2024_clean$TRANTIME)),
        sum(!is.na(acs2024_clean$INCTOT))),
  Mean = c(mean(acs2024_clean$AGE, na.rm = TRUE),
          mean(acs2024_clean$female, na.rm = TRUE),
          mean(acs2024_clean$less_than_hs, na.rm = TRUE),
          mean(acs2024_clean$hs_only, na.rm = TRUE),
          mean(acs2024_clean$some_college, na.rm = TRUE),
          mean(acs2024_clean$college_only, na.rm = TRUE),
          mean(acs2024_clean$advanced_degree, na.rm = TRUE),
          mean(acs2024_clean$employed, na.rm = TRUE),
          mean(acs2024_clean$unemployed, na.rm = TRUE),
          mean(acs2024_clean$not_in_labor_force, na.rm = TRUE),
          mean(acs2024_clean$TRANTIME, na.rm = TRUE),
          mean(acs2024_clean$INCTOT, na.rm = TRUE)),
  SD = c(sd(acs2024_clean$AGE, na.rm = TRUE),
          sd(acs2024_clean$female, na.rm = TRUE),
          sd(acs2024_clean$less_than_hs, na.rm = TRUE),
          sd(acs2024_clean$hs_only, na.rm = TRUE),
          sd(acs2024_clean$some_college, na.rm = TRUE),
          sd(acs2024_clean$college_only, na.rm = TRUE),
          sd(acs2024_clean$advanced_degree, na.rm = TRUE),
          sd(acs2024_clean$employed, na.rm = TRUE),
          sd(acs2024_clean$unemployed, na.rm = TRUE),
          sd(acs2024_clean$not_in_labor_force, na.rm = TRUE),
          sd(acs2024_clean$TRANTIME, na.rm = TRUE),
          sd(acs2024_clean$INCTOT, na.rm = TRUE)),
  Min = c(min(acs2024_clean$AGE, na.rm = TRUE),
          min(acs2024_clean$female, na.rm = TRUE),
          min(acs2024_clean$less_than_hs, na.rm = TRUE),
          min(acs2024_clean$hs_only, na.rm = TRUE),
          min(acs2024_clean$some_college, na.rm = TRUE),
          min(acs2024_clean$college_only, na.rm = TRUE),
          min(acs2024_clean$advanced_degree, na.rm = TRUE),
          min(acs2024_clean$employed, na.rm = TRUE),
          min(acs2024_clean$unemployed, na.rm = TRUE),
          min(acs2024_clean$not_in_labor_force, na.rm = TRUE),
          min(acs2024_clean$TRANTIME, na.rm = TRUE),
          min(acs2024_clean$INCTOT, na.rm = TRUE)),
  Max = c(max(acs2024_clean$AGE, na.rm = TRUE),
          max(acs2024_clean$female, na.rm = TRUE),
          max(acs2024_clean$less_than_hs, na.rm = TRUE),
          max(acs2024_clean$hs_only, na.rm = TRUE),
          max(acs2024_clean$some_college, na.rm = TRUE),
          max(acs2024_clean$college_only, na.rm = TRUE),
          max(acs2024_clean$advanced_degree, na.rm = TRUE),
          max(acs2024_clean$employed, na.rm = TRUE),
          max(acs2024_clean$unemployed, na.rm = TRUE),
          max(acs2024_clean$not_in_labor_force, na.rm = TRUE),
          max(acs2024_clean$TRANTIME, na.rm = TRUE),
          max(acs2024_clean$INCTOT, na.rm = TRUE)))

knitr::kable(summary_stats_table, digits = 1,
             caption = "Table 1: Summary Statistics for 2024 ACS Sample")

#Question 6
#Based on this table, the maximum commute time taken is 195 minutes or 
#approximately 3 hours and 15 minutes. I suppose this commute time could be a 
#daily commute, but is far beyond the amount of time I would drive as a daily 
#commute. If the money or experience is good enough I am sure one could be 
#compelled to do anything. 



```

3. Who Should Be In Your Analysis
```{r}
#Question 1
sum(acs2024_clean$TRANTIME == 0, na.rm = TRUE)
#there are 2062945 people that have TRANTIME equal to zero.

length(na.omit(acs2024_clean$TRANTIME))

(2062945 / 3422888) * 100
#This percentage is 60.27%



acs2024_test <- acs2024_clean %>% 
  group_by(EMPSTAT) %>% 
  summarise(trantimes = mean(TRANTIME, na.rm = TRUE),
            n = sum(!is.na(TRANTIME)))
print(acs2024_test)

#It is likely that these people who do not have a commute time are those that 
#are n/a, unemployed or not in the labor force as displayed in the table below.  

#Question 2
commuters <- acs2024_clean %>% 
  filter(EMPSTAT == 1, TRANTIME > 0) %>% 
  select(AGE, female, less_than_hs, hs_only, some_college, college_only, 
         advanced_degree, employed,TRANTIME, INCTOT)
#The only people who wouldn't have a commute would be those that are not 
#commuting to work or who work from home. As such, those that are unemployed or
#not in the labor force would not count.  Thus, the only people included in the 
#commuter subset are those that are employed and who have a commute time of 
#greater than zero minutes.

#Question 3
#Trantime Data with commuter subset
nrow(commuters)
#there are now 1359943 observations in our new subset.
min(commuters$TRANTIME)
#the new min trantime is 1. This makes sense as for those that commute to their 
#office of employment they can not travel zero minutes unless they work from 
#home.  We weeded these people out by doing TRANTIME>0, to get just people that 
#actually commute into their place of work.

#Question 4
summary_stats_table2  <- data.frame(
  Variable = c("Age", "Female", "Less than High School", "High School Only",
  "Some College", "College Only", "Advanced Degree", "Employed", 
  "Commute Time (mins)", "Total Income ($)"),
  N = c(sum(!is.na(commuters$AGE)),
        sum(!is.na(commuters$female)),
        sum(!is.na(commuters$less_than_hs)),
        sum(!is.na(commuters$hs_only)),
        sum(!is.na(commuters$some_college)),
        sum(!is.na(commuters$college_only)),
        sum(!is.na(commuters$advanced_degree)),
        sum(!is.na(commuters$employed)),
        sum(!is.na(commuters$TRANTIME)),
        sum(!is.na(commuters$INCTOT))),
 Mean = c(mean(commuters$AGE, na.rm = TRUE),
          mean(commuters$female, na.rm = TRUE),
          mean(commuters$less_than_hs, na.rm = TRUE),
          mean(commuters$hs_only, na.rm = TRUE),
          mean(commuters$some_college, na.rm = TRUE),
          mean(commuters$college_only, na.rm = TRUE),
          mean(commuters$advanced_degree, na.rm = TRUE),
          mean(commuters$employed, na.rm = TRUE),
          mean(commuters$TRANTIME, na.rm = TRUE),
          mean(commuters$INCTOT, na.rm = TRUE)),
 SD = c(sd(commuters$AGE, na.rm = TRUE),
          sd(commuters$female, na.rm = TRUE),
          sd(commuters$less_than_hs, na.rm = TRUE),
          sd(commuters$hs_only, na.rm = TRUE),
          sd(commuters$some_college, na.rm = TRUE),
          sd(commuters$college_only, na.rm = TRUE),
          sd(commuters$advanced_degree, na.rm = TRUE),
          sd(commuters$employed, na.rm = TRUE),
          sd(commuters$TRANTIME, na.rm = TRUE),
          sd(commuters$INCTOT, na.rm = TRUE)),
  Min = c(min(commuters$AGE, na.rm = TRUE),
          min(commuters$female, na.rm = TRUE),
          min(commuters$less_than_hs, na.rm = TRUE),
          min(commuters$hs_only, na.rm = TRUE),
          min(commuters$some_college, na.rm = TRUE),
          min(commuters$college_only, na.rm = TRUE),
          min(commuters$advanced_degree, na.rm = TRUE),
          min(commuters$employed, na.rm = TRUE),
          min(commuters$TRANTIME, na.rm = TRUE),
          min(commuters$INCTOT, na.rm = TRUE)),
  Max = c(max(commuters$AGE, na.rm = TRUE),
          max(commuters$female, na.rm = TRUE),
          max(commuters$less_than_hs, na.rm = TRUE),
          max(commuters$hs_only, na.rm = TRUE),
          max(commuters$some_college, na.rm = TRUE),
          max(commuters$college_only, na.rm = TRUE),
          max(commuters$advanced_degree, na.rm = TRUE),
          max(commuters$employed, na.rm = TRUE),
          max(commuters$TRANTIME, na.rm = TRUE),
          max(commuters$INCTOT, na.rm = TRUE)))


knitr::kable(summary_stats_table2, digits = 1,
             caption = "Table 2: Summary Statistics for Commuters")



```
4. Visualize and Interpret

```{r}
#Question 1
library(ggplot2)

ggplot(commuters, aes (x =TRANTIME)) +
  geom_histogram(binwidth = 9, fill = "steelblue",
                 color = "white") +
  labs(x ="Commute Time (mins)",
       y = "Count",
       title = "Distribution of Commute Times from Respondents' Homes to Work")

ggsave("output/commute histogram.png")

#Question 2
#This histogram is definitely one that is right skewed. The center is around 
#27ish which is also the commuter subsets trantime mean. It is interesting to 
#see there is a significant spike at about 20 and then there is no data reported 
#for just past 100 to 125. We then see a few additional observation units at 
#around 150. 

#Question 3
mean(commuters$TRANTIME, na.rm = TRUE)
#The mean of the data 27.21505. 
median(commuters$TRANTIME, na.rm = TRUE)
#The median of the data is 20.

#This implies that because the mean is greater that the median the graph is 
#right skewed. We know this because mean > median --> right-skewed. This makes 
#sense because the mean places more weight on outliers. We see this exact 
#right-skew in the created histogram. 


```
